### ISSUE TITLE
Deleting an Item does not replace its name with the name of the item below it

### ISSUE THREAD

**Issue by Mulley** [sansarip/nw-calculator#1]
Love the tool! Wanted to drop a quick issue for a tiny bug.

# Steps to Reproduce

1. Search for any item and select it (ie: **Iron War Hammer**)
2. Click **Add Another Item**
3. Search for any other item and select it (ie: **Coarse Leather Gloves**)
4. Click the trashcan icon for the first item (**Iron War Hammer**)

# Expected Result
The list shifts up. All information from the card below populates the first card.

# Actual Result
The list shifts up. All information **except the item name** populates the first card

[Screenshots](https://imgur.com/a/3OGZMuI)

**Comment by sansarip** [comment]
Thanks for the report! I see the issue and will address it shortly 🔍

**Comment by sansarip** [comment]
After being fed magical beans, the metamorphosed bug fluttered away 🐛 -> 🦋 

It was a React key issue 🔑  Lemme know if you are still experiencing it and I can reopen the issue!
