### ISSUE TITLE
Coarse Leather Using Incorrect Material

### ISSUE THREAD

**Issue by sammullican** [sansarip/nw-calculator#4]
**Describe the bug**
When adding items that require leather to the calculator, the calculator shows 3x [Rawhide Scraps](https://nwdb.info/db/item/rawhidet0) for Coarse Leather which are not available in-game.

**To Reproduce**
1. Go to [https://www.newworldcraft.io/](https://www.newworldcraft.io/)
2. Click on 'Search for an item'
3. Enter 'Coarse Leather'
4. See incorrect crafting requirements

**Expected behavior**
Recipes for items requiring leather should use 4x [Rawhide](https://nwdb.info/db/item/rawhidet1) instead when referring to Coarse Leather.

**Screenshots**
![image](https://user-images.githubusercontent.com/22376358/137811403-21d95094-3501-49d6-a8ed-e9104b2d4c7c.png)
![image](https://user-images.githubusercontent.com/22376358/137811463-f9042f24-37c0-431a-97c8-6c890741cbe1.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 10.0.19043 Build 19043
 - Brave
 - Version 1.30.89 Chromium: 94.0.4606.81 (Official Build) (64-bit)

**Additional context**
Love the calculator and appreciate what you do!

**Comment by sansarip** [comment]
Hey friend! Thanks for the issue! This is more so an problem with the data I get from [nwdb.info](nwdb.info) - which I don't manage. But, I'll implement a temporary fix soon!
