### ISSUE TITLE
Obsidian Voidstone/Lodestone Brick - Wrong Lodestone

### ISSUE THREAD

**Issue by DTM450** [sansarip/nw-calculator#5]
**Describe the bug**
Obsidian Voidstone and Lodestone Brick uses the wrong lodestone.

**To Reproduce**
N/A

**Expected behavior**
Obsidian Voidstone and Lodestone Brick should use standard lodestone

**Screenshots**
![firefox_2021-12-26_15-09-15](https://user-images.githubusercontent.com/9582395/147399047-2d23d37c-73d1-4232-b4c1-933a77dcf3f8.png)
![firefox_2021-12-26_15-09-40](https://user-images.githubusercontent.com/9582395/147399048-532b96b9-f640-4f37-9200-90ab281bef54.png)

**Comment by sansarip** [comment]
Thank you for raising this issue! I should have a fix up soon 👍

**Comment by sansarip** [comment]
Should be fixed now 🤜 🐛 ✅ 

![voidstone screenshot](https://i.gyazo.com/b20ffaa0119855ad5503a5c98f387963.png)
