### ISSUE TITLE
Scrolling through recipes 

### ISSUE THREAD

**Issue by botflakes** [sansarip/nw-calculator#6]
**Is your feature request related to a problem? Please describe.**
I would like to scroll to the recipes. For example, if you type Linen you get many recipes but you can select the one for Linen

**Describe the solution you'd like**
Lets scroll trough the recipes 

**Additional context**
![fSd5XY](https://user-images.githubusercontent.com/69024038/151472937-f5c6a76e-1a9a-497a-a80b-cd59f5c2dd3e.png)

Would really like to see this soon and I would like to thank you for the craft calculator!

EDIT:

Just discovered that when you type "Leinen" the recipe for "Linen" will actually show up

**Comment by sansarip** [comment]
Yea, thanks for raising this issue! I think it's about time I implement a scrolling item view. I'll work on it!

**Comment by sansarip** [comment]
Fixed! Feel free to reopen this issue if you're still having troubles 👍

**Comment by botflakes** [comment]
Nice, thanks for the quick bug fix and adding scrolling 👍
