### ISSUE TITLE
How to get new crafts?

### ISSUE THREAD

**Issue by SourCandy80** [sansarip/nw-calculator#8]
Hello!

It seems this project has been abandoned. I want to make an arbitrage calculator, and this is the only project I have found that has a list of all the items you can craft and the items needed to craft them. 

Would you happen to know a way I can get a list of craftable items + recipes? I tried looking for the code you used to scrape the data, but couldn't find it. 

Thanks!

Edit: Never mind I have just found the scraper. I have have never heard of this language before though so that is going to make it difficult for me ;(

**Comment by sansarip** [comment]
Hi, you can view the makefile to find the scrape commands! I got the data for the app from nwdb. I tried scraping again recently, but the data I put together was a little wonky. It seems like I'll need to update my scraper code to account for the changes in nwdb, but I can't promise when/if that'll happen!

**Comment by SourCandy80** [comment]
RIP that sucks. Was really hoping I could make something simple tonight. Should be really easy profit assuming you still play new world :D

Just wish someone had a public db of recipes :(

Thanks again!
